const {test}=require('node:test');const a=require('node:assert/strict');const handler=require('../api/index');const {merge,view,validate}=handler._test;
const cli=(id,colab)=>({id,colab,emp:'Empresa',st:'Lead',sv:[],pays:[],hist:[],et:{},fech:'',fim:''});
const state=()=>({colabs:[{id:1,nome:'Gabi',com:60},{id:2,nome:'Laura',com:60}],clients:[cli(10,1),cli(20,2)]});const gabi={id:'gabi',role:'user',colab_id:1};
test('consulta entrega somente carteira própria',()=>{const v=view(state(),gabi,[gabi]);a.deepEqual(v.clients.map(c=>c.id),[10]);a.equal(v.colabs.length,1);a.equal(v.users[0].h,undefined)});
test('bloqueia transferência e captura de cliente alheio',()=>{a.throws(()=>merge(state(),{clients:[cli(10,2)]},gabi),e=>e.status===403);a.throws(()=>merge(state(),{clients:[cli(20,1)]},gabi),e=>e.status===403)});
test('preserva clientes alheios e comissão ao gravar carteira própria',()=>{const next=merge(state(),{colabs:[{id:1,nome:'Gabi',com:100}],clients:[{...cli(10,1),emp:'Nova'}]},gabi);a.equal(next.colabs[0].com,60);a.equal(next.clients.find(c=>c.id===20).emp,'Empresa');a.equal(next.clients.find(c=>c.id===10).emp,'Nova')});
test('valida valores, IDs e status para impedir injeção de HTML',()=>{const s=state();s.clients[0].pays=[{v:-1,pago:true}];a.throws(()=>validate(s));const d=state();d.clients.push(cli(10,1));a.throws(()=>validate(d));const x=state();x.clients[0].st='<img onerror=alert(1)>';a.throws(()=>validate(x))});
test('administrador pode transferir carteira',()=>{const s=state();s.clients[0].colab=2;a.equal(merge(state(),s,{role:'admin'}).clients[0].colab,2)});
const res=()=>({setHeader(){},status(s){this.code=s;return this},json(v){this.value=v;return this}});
const req=(method,route,body,headers={})=>({method,query:{route},body,headers:{host:'agr.example',origin:'https://agr.example',cookie:'agr_access=token',...headers}});
async function mock(fn){const old=global.fetch;const keys=['SUPABASE_URL','SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY'];const oldEnv=keys.map(k=>process.env[k]);Object.assign(process.env,{SUPABASE_URL:'https://test.supabase.co',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service'});let row={id:1,version:0,data:state()};global.fetch=async(url,opts={})=>{const u=new URL(url);let data;if(u.pathname==='/auth/v1/user')data={id:'gabi'};else if(u.pathname==='/rest/v1/agr_profiles')data=[{...gabi,nome:'Gabi',email:'gabi@example.com'}];else if(u.pathname==='/rest/v1/agr_state'){if(opts.method==='PATCH'){if(u.searchParams.get('version')!==`eq.${row.version}`)data=[];else{row={...row,...JSON.parse(opts.body)};data=[structuredClone(row)]}}else data=[structuredClone(row)]}else throw Error(url);return{ok:true,status:200,json:async()=>data}};try{await fn(()=>row)}finally{global.fetch=old;keys.forEach((k,i)=>oldEnv[i]===undefined?delete process.env[k]:process.env[k]=oldEnv[i])}}
test('API exige sessão e bloqueia outra origem',async()=>{const x=res();await handler(req('GET','state',{}, {cookie:''}),x);a.equal(x.code,401);const y=res();await handler(req('PUT','state',{}, {origin:'https://other.example'}),y);a.equal(y.code,403)});
test('gravações simultâneas não sobrescrevem silenciosamente',async()=>{await mock(async get=>{const x=res(),y=res();await Promise.all([handler(req('PUT','state',{version:0,state:{clients:[{...cli(10,1),emp:'A'}]}}),x),handler(req('PUT','state',{version:0,state:{clients:[{...cli(10,1),emp:'B'}]}}),y)]);a.deepEqual([x.code,y.code].sort(),[200,409]);a.equal(get().version,1);a.equal(get().data.clients.find(c=>c.id===20).emp,'Empresa')})});
test('colaborador não cria administradores',async()=>{await mock(async()=>{const x=res();await handler(req('POST','users',{role:'admin'}),x);a.equal(x.code,404)})});
test('API não retorna cliente alheio',async()=>{await mock(async()=>{const x=res();await handler(req('GET','state'),x);a.equal(x.code,200);a.deepEqual(x.value.state.clients.map(c=>c.id),[10])})});
