const {test}=require('node:test');
const a=require('node:assert/strict');
const handler=require('../api/index');
const {merge,view,validate,passwordRecord,passwordOk}=handler._test;
const cli=(id,colab)=>({id,colab,emp:'Empresa',st:'Lead',sv:[],pays:[],hist:[],et:{},fech:'',fim:''});
const state=()=>({colabs:[{id:1,nome:'Gabi',com:60},{id:2,nome:'Laura',com:60}],clients:[cli(10,1),cli(20,2)]});
const gabi={id:'gabi',role:'user',colabId:1,ownerId:'admin'};
test('consulta entrega somente carteira própria',()=>{const v=view(state(),gabi,[gabi]);a.deepEqual(v.clients.map(c=>c.id),[10]);a.equal(v.colabs.length,1);a.equal(v.users[0].passwordHash,undefined)});
test('bloqueia transferência e captura de cliente alheio',()=>{a.throws(()=>merge(state(),{clients:[cli(10,2)]},gabi),e=>e.status===403);a.throws(()=>merge(state(),{clients:[cli(20,1)]},gabi),e=>e.status===403)});
test('preserva clientes alheios e comissão ao gravar carteira própria',()=>{const next=merge(state(),{colabs:[{id:1,nome:'Gabi',com:100}],clients:[{...cli(10,1),emp:'Nova'}]},gabi);a.equal(next.colabs[0].com,60);a.equal(next.clients.find(c=>c.id===20).emp,'Empresa');a.equal(next.clients.find(c=>c.id===10).emp,'Nova')});
test('valida valores, IDs e status',()=>{const s=state();s.clients[0].pays=[{v:-1,pago:true}];a.throws(()=>validate(s));const d=state();d.clients.push(cli(10,1));a.throws(()=>validate(d));const x=state();x.clients[0].st='<img onerror=alert(1)>';a.throws(()=>validate(x))});
test('administrador pode transferir carteira',()=>{const s=state();s.clients[0].colab=2;a.equal(merge(state(),s,{role:'admin'}).clients[0].colab,2)});
test('senha usa hash e valida corretamente',()=>{const u={...passwordRecord('senha-super-segura-123')};a.equal(passwordOk(u,'senha-super-segura-123'),true);a.equal(passwordOk(u,'senha-errada'),false);a.equal(u.passwordHash.includes('senha-super'),false)});
